<a href="https://colab.research.google.com/github/IzzuddinSuib/ml-zoomcamp-homework/blob/main/linear_algebra_refresher.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np
import pandas as pd

In [4]:
u = np.array([2,4,5,6])
u

array([2, 4, 5, 6])

In [5]:
v = np.array([1,0,0,2])
v

array([1, 0, 0, 2])

In [6]:
u+v

array([3, 4, 5, 8])

In [7]:
2*u

array([ 4,  8, 10, 12])

In [8]:
# dot product

u*v

array([ 2,  0,  0, 12])

In [10]:
v.shape[0]

4

In [12]:
# rvec * cvec

def vector_vector_multiplication(u,v):
  assert u.shape[0] == v.shape[0]

  n= u.shape[0]

  result = 0.0

  for i in range(n):
    result = result + u[i]*v[i]

  return result


In [13]:
vector_vector_multiplication(u,v)

np.float64(14.0)

In [14]:
u.dot(v)

np.int64(14)

In [15]:
# matrix vector multiplication

U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [17]:
U.shape

(3, 4)

In [18]:
np.zeros(3)

array([0., 0., 0.])

In [19]:
def matrix_vector_multiplication(U,v):
  assert U.shape[1] == v.shape[0]

  num_rows = U.shape[0]

  result = np.zeros(num_rows)

  for i in range(num_rows):
    result[i] = vector_vector_multiplication(U[i],v)

  return result


In [21]:
matrix_vector_multiplication(U,v)

array([14.,  5.,  5.])

In [22]:
U.dot(v)

array([14,  5,  5])

In [23]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [26]:
# matrix matrix multiplication

def matrix_matrix_multiplication(U,V):
  assert U.shape[1] == V.shape[0]

  num_rows = U.shape[0]
  num_cols = V.shape[1]

  result = np.zeros((num_rows,num_cols))

  for i in range(num_cols):
    vi = V[:,i]
    Uvi = matrix_vector_multiplication(U,vi)
    result[:,i] = Uvi

  return result

In [29]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [30]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [27]:
matrix_matrix_multiplication(U,V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [28]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [33]:
# Identity matrix

I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [35]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [37]:
# Matrix inverse

Vs = V[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [40]:
Vs_inv = np.linalg.inv(Vs)
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [41]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])